spring:
  ## mysql db
  #  h2:
  #    console:
  #      enabled: true
  #      path:
  #  datasource:
  ##    url: jdbc:mysql://wrieating-database.ca59q4wbjg2d.ap-northeast-2.rds.amazonaws.com:13306/wrieatingdb
  #    url: jdbc:mysql://localhost:3306/wrieatingdb
  #    username: root
  #    password: Taskforce@1
  #    driver-class-name:
  #  sql:
  #    init:
  #      data-locations:
  #      mode: always
  #  jpa:
  #    database-platform: org.hibernate.dialect.MySQL5Dialect
  #    hibernate:
  #  h2 db
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true  # 데이터 소스 초기화 지연 설정
  #    open-in-view: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
  mail:
    host: smtp.gmail.com
    port: 587
    username: cheche7728@gmail.com
    password: whku rczz rcrm ewxj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
email:
  sender:
    man: cheche7728@gmail.com
    password: whku rczz rcrm ewxj

#jwt
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: qweasdzxcrtyfghvbn12341234qweasdzxcrtyfghvbn345345345345345sdasdhukwhdkuahjhdu
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

server:
  error:
    whitelabel:
      enabled: false